version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      rent-network:
        ipv4_address: 172.18.0.2
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ANSKk08aPEDbFjDO
      MYSQL_DATABASE: testing
    ports:
      - "3307:3306"
    networks:
      rent-network:
        ipv4_address: 172.18.0.3
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      rent-network:
        ipv4_address: 172.18.0.4

networks:
  rent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16